galaxy_info:
  author: Miroslav Hudec
  description: Role_Description_TBD
  company: Company_TBD

  license: License_TBD

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies:
  - role: mihudec.net_ansible.run_preparation

